name: bastion host
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code 
        uses: actions/checkout@v2

      - name: deploy
        run: |
          echo "deploying to bastion host"
          echo "done"

      - name: clone repo
        run: |
          echo "cloning repo"
          git clone https://github.com/pdyke/napa.git
          echo "done"
      
      - name: copy files
        run: |
          echo "copying files"
          scp -i /home/pdyke/Downloads/testament.pem -o ProxyCommand="ssh -i testament.pem ubuntu@ip-10-0-1-115 -W %h:%p" napa ubuntu@10.0.2.222:~/napa
          echo "done"