name: bastion host
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code 
        uses: actions/checkout@v2

      - name: deploy
        run: |
          echo "deploying to bastion host"
          echo "done"

      - name: clone repo
        run: |        
          echo "cloning repo"
          cd /home/ubuntu
          git clone https://github.com/pdyke/napa.git
          cd napa
          pwd
          echo "done"
      
      - name: copy files
        run: |
          echo "copying files"
          scp -i /home/ubuntu/testament.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i /home/ubuntu/testament.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@13.49.245.166 -W %h:%p" /home/ubuntu/napa ubuntu@10.0.2.38:/home/ubuntu/napa
          echo "done"