name: bastion host
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code 
        uses: actions/checkout@v2

      - name: deploy
        run: |
          echo "deploying to bastion host"
          echo "done"

      - name: clone repo
        run: |
          echo "cloning repo"
          git clone https://github.com/pdyke/napa.git
          echo "done"
      
      - name: copy files
        run: |
          echo "copying files"
          scp -i /home/ubuntu/testament.pem -o ProxyCommand="ssh -i /home/ubuntu/testament.pem ubuntu@ip-10-0-1-115 -W %h:%p" /home/ubuntu/actions-runner/_work/bostion-host/bostion-host/napa ubuntu@10.0.2.222:/home/ubuntu/napa
          echo "done"